name: Add

on: 
  workflow_dispatch:
    inputs:
      url: 
        description: 'URL to the repository'
        required: true
    

jobs:
  add_and_validate:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.0"
      - uses: actions/checkout@v2
      - name: "Add Package to JSON"
        run: jq ". |= . + [\"${{ github.event.inputs.name }}\"]\" packages.json > packages.json"
      - name: Validate
        run: swift ./validate.swift
        
        
